### ISSUE TITLE
service httpd start  Not WORK! 

### ISSUE THREAD

**Issue by XxSkydevil06xX** [parkervcp/guides#1]

**Comment by parkervcp** [comment]
No notes on which one you were saying this was for? I will guess it was for the CentOS 6 guide.

**Comment by XxSkydevil06xX** [comment]
No CentOS 7

**Comment by parkervcp** [comment]
Which guide are you following. I just want to be sure.

**Comment by XxSkydevil06xX** [comment]
CentOS 7

**Comment by parkervcp** [comment]
You should be following this guide where the line "service httpd start" isn't even mentioned.

https://github.com/parkervcp/guides/blob/master/Puffer%20Panel/CentOS%207/Panel-httpd.md
